### PR TITLE
fix: skybox reflections

### PR DESCRIPTION
**Pull request by Kinerius**
## What does this PR change?

Fixes https://github.com/decentraland/explorer-desktop/issues/119

## How to test the changes?

Go to genesis plaza, the water should reflect the sky in real-time.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Comment by Reach2N** [comment]
That's kind of an unnecessary thing for me. take a lot of usages and stressing my PC.  I want the best performance over quality.

**Comment by Kinerius** [comment]
> That's kind of an unnecessary thing for me. take a lot of usages and stressing my PC. I want the best performance over quality.

Performance impact is quite minimal, this fixes a lot of textures being black.
Also, this is enabled in the WebGL renderer.

**Review by pravusjif — APPROVED** [review]
I approve it because we have this ON in the web client, but this change doesn't fix any of the reported visual problems in the issue https://github.com/decentraland/explorer-desktop/issues/119 =S

**Comment by Kinerius** [comment]
> I approve it because we have this ON in the web client, but this change doesn't fix any of the reported visual problems in the issue #119 =S

You are right, It seems to be working differently on the desktop client than in unity, I'm going to keep investigating what is the cause

**Comment by Kinerius** [comment]
Unity
image

Standalone
image

**Review by kuruk-mm — APPROVED** [review]

**Pull request merged**
